cloudstack:
  host: 'localhost'
  port: 8080
  apiport: 8096

infrastructure:
  zones:
    - name:          'testzone'
      networktype:   'Basic'
      public_dns1:   '168.95.1.1'
      public_dns2:
      internal_dns1:
      internal_dns2: '168.95.1.1'
      hypervisor:    'xen'
      public:        true
      localstorage:  false
      enable:        true
      networks:
        - name: 'DefaultGuestNetwork'
          networkoffering: 'DefaultSharedNetworkOfferingWithSGService'
      physicalnetworks:
        - name: 'testphysicalnetwork1'
      pods:
        - name:         'testpod'
          gateway:      '192.168.56.254'
          netmask:      '255.255.255.0'
          startip:      '192.168.56.51'
          endip:        '192.168.56.70'
          vlan_startip: '192.168.56.71'
          vlan_endip:   '192.168.56.100'
          vlan_forvirtual: false
          clusters:
            - name:        'testcluster'
              hypervisor:  'XenServer'
              clustertype: 'CloudManaged'
              storagepools: 
                - name:  'pri'
                  scope: 'cluster'
                  url:   'nfs://192.168.56.1/exports/pri'
                  tags:  'pri'
              hosts:
                - ip:       'http://192.168.56.10'
                  username: 'root'
                  password: 'password'
                  tags:     'xen'
      secondarystorages:
        - ip:   '192.168.56.1'
          path: '/exports/sec'

accounts:
   domains:
     - name: 'ROOT'
       accounts:
         #ROOT domain Admin account
         - accounttype:    2
           username:       'rootadmin1'
           password:       'novirus'
           email:          'rootadmin1@test.com'
           first_name:     'rootadmin1'
           last_name:      'rootadmin1'
           account:        'rootadmin'
           time_zone:
           network_domain:
           users:
             - username:   'rootadmin1_1'
               email:      'rootadmin1_1@test.com'
               first_name: 'rootadmin1_1'
               last_name:  'rootadmin1_1'
               password:   'novirus'
               time_zone: 
         # ROOT domain User account
         - accounttype:    0
           username:       'rootuser1'
           password:       'novirus'
           email:          'rootuser1@test.com'
           first_name:     'rootuser1'
           last_name:      'rootuser1'
           account:        'rootuser'
           time_zone:
           network_domain:
       domains:
         - name: 'domain1'
           network_domain:
           accounts:
             - accounttype:    2
               email:          'domain1admin1@test.com'
               first_name:     'domain1admin1'
               last_name:      'domain1admin1'
               username:       'domain1admin1'
               account:        'domain1admin'
               password:       'novirus'
               type:           'Admin'
               time_zone:
               network_domain:
             - accounttype:    0
               email:          'domain1user1@test.com'
               first_name:     'domain1user1'
               last_name:      'domain1user1'
               username:       'domain1user1'
               account:        'domain1user'
               password:       'novirus'
               type:           'User'
               time_zone:
               network_domain:
           domains:
             - name: 'domain1-1'
               network_domain:
               accounts:
                 - accounttype:    2
                   email:          'domain1-1admin1@test.com'
                   first_name:     'domain1-1admin1'
                   last_name:      'domain1-1admin1'
                   username:       'domain1-1admin1'
                   account:        'domain1-1admin'
                   password:       'novirus'
                   type:           'Admin'
                   time_zone:
                   network_domain:
                 - accounttype:    0
                   email:          'domain1user1@test.com'
                   first_name:     'domain1-1user1'
                   last_name:      'domain1-1user1'
                   username:       'domain1-1user1'
                   account:        'domain1-1user'
                   password:       'novirus'
                   type:           'User'
                   time_zone:
                   network_domain:

         - name: 'domain2'
           network_domain:
           accounts:
             - accounttype:    2
               email:          'domain2admin1@test.com'
               first_name:     'domain2admin1'
               last_name:      'domain2admin1'
               username:       'domain2admin1'
               account:        'domain2admin'
               password:       'novirus'
               type:           'Admin'
               time_zone:
               network_domain:
             - accounttype:    0
               email:          'domain2user1@test.com'
               first_name:     'domain2user1'
               last_name:      'domain2user1'
               username:       'domain2user1'
               account:        'domain2user'
               password:       'novirus'
               type:           'User'
               time_zone:
               network_domain:
           
